# An incredibly useful tool for defining generic tasks for your project.
# Poetry initialization
init: ## Initialize Poetry and install dependencies
	@rm -rf .venv
	@poetry install

# Run tests
test: ## Run tests using pytest
	@poetry run pytest